Repository chingu-voyage6/Geckos-Team-10, pull requests merged in 2018-07, with the labels that each got.

#17 Feature/toolbar right dropdown
  src/components/App/App.js
  src/components/Boards/Boards.styles.js
  src/components/Home/Home.js
  src/components/Home/Home.styles.js
  src/components/Home/components/LeftSidebar/LeftSidebar.js
  src/components/Home/components/LeftSidebar/LeftSidebar.styles.js
  src/components/Home/components/MainContent/MainContent.js
  src/components/Home/components/RightSidebar/RightSidebar.js
  src/components/Toolbar/Toolbar.js
  src/components/Toolbar/Toolbar.styles.js
  src/components/Toolbar/components/PopOver/PopOver.js
  src/components/Toolbar/components/PopOver/PopOver.styles.js
  src/services/auth.js
  src/stupidData.js
Labels: enhancement, quickfix

#16 Home.js - started child components
  src/components/Home/Home.js
  src/components/Home/Home.styles.js
  src/components/Home/components/LeftSidebar/LeftSidebar.js
  src/components/Home/components/LeftSidebar/LeftSidebar.styles.js
  src/components/Home/components/MainContent/MainContent.js
  src/components/Home/components/RightSidebar/RightSidebar.js
  src/stupidData.js
Labels: enhancement

#18 Refactor: Styled components file
  .eslintrc.js
  src/components/Board/Board.js
  src/components/Board/BoardProvider.js
  src/components/Board/components/List/List.js
  src/components/Board/components/List/components/CardTask/CardTask.js
  src/components/Board/components/List/components/CardTask/CardTask.styles.js
  src/components/Board/components/List/components/ListFooter/ListFooter.js
  src/components/Board/components/List/components/ListFooter/ListFooter.styles.js
  src/components/Board/components/List/components/ListHeader/ListHeader.js
  src/components/Board/components/List/components/ListHeader/ListHeader.styles.js
  src/components/Board/components/List/components/ListMenu/ListMenu.js
  src/components/Board/components/List/components/ListMenu/ListMenu.styles.js
  src/components/Board/components/List/components/Modal/Modal.js
  src/components/Board/components/List/components/index.js
  src/components/StyledComponents/Button.js
  src/components/StyledComponents/Label.js
  src/components/StyledComponents/index.js
Labels: refactor

#21 Add basic modal
  package.json
  src/components/Board/Board.js
  src/components/Board/BoardProvider.js
  src/components/Board/components/List/List.js
  src/components/Board/components/List/List.styles.js
  src/components/Board/components/List/components/CardTask/CardTask.js
  src/components/Board/components/Modal/Modal.js
  src/components/Board/components/Modal/Modal.styles.js
  src/components/StyledComponents/Button.js
  src/components/StyledComponents/Label.js
  src/dummyData.js
Labels: enhancement

#23 Add loading spinner when the user logs in or out
  README.md
  src/components/App/App.js
  src/components/Callback/Callback.js
  src/components/Callback/Callback.styles.js
  src/components/Components.js
  src/components/Home/Home.js
  src/components/LoggedOut/LoggedOut.js
  src/services/auth.js
Labels: enhancement

#27 Add graphcool endpoint
  package.json
  src/components/App/App.js
  src/components/Board/Board.js
  src/components/Board/components/List/List.js
  src/components/Board/components/List/components/CardTask/CardTask.js
  src/graphql/queries/all-boards.gql
  src/graphql/queries/board.gql
  src/graphql/queries/index.js
  src/index.js
Labels: enhancement

#33 Task modal
  .eslintrc.js
  README.md
  package-lock.json
  package.json
  src/components/Board/Board.js
  src/components/Board/BoardProvider.js
  src/components/Board/components/List/List.js
  src/components/Board/components/List/components/CardTask/CardTask.js
  src/components/Board/components/Modal/Modal.js
  src/components/Board/components/Modal/Modal.styles.js
  src/components/Board/components/Modal/components/AddTagMenu.js
  src/components/Board/components/Modal/components/AddTagMenu.styles.js
  src/components/Home/components/LeftSidebar/LeftSidebar.js
  src/index.js
Labels: enhancement

#34 [WIP] Get userId from GraphQl using Auth0 credentials
  src/components/App/App.js
  src/components/Board/Board.js
  src/components/Home/Home.js
  src/components/Home/components/BoardsHome/BoardsHome.js
  src/components/Home/components/BoardsHome/BoardsHome.styles.js
  src/components/Home/components/LeftSidebar/LeftSidebar.js
Labels: enhancement

#37 Close boards sidebar when clicking outside
  src/components/Boards/Boards.js
  src/components/Toolbar/Toolbar.js
Labels: enhancement
