Repository chingu-voyage6/Geckos-Team-10, pull requests merged in 2018-06, with the labels that each got.

#1 Add eslint & others configurations
  .eslintignore
  .eslintrc.js
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/config.yml
  .github/stale.yml
  CONTRIBUTING.md
  package-lock.json
  package.json
  server.js
  src/components/App/App.js
  src/components/App/App.test.js
  src/components/Board/Board.js
  src/components/Components.js
  src/components/Home/Home.js
  src/components/Login/Login.js
  src/components/Profile/Profile.js
  src/components/Signup/Signup.js
  src/index.js
  yarn.lock
Labels: enhancement

#2 Added integration with Auth0
  .eslintignore
  package-lock.json
  package.json
  src/components/App/App.js
  src/components/Callback/Callback.css
  src/components/Callback/Callback.js
  src/components/Components.js
  src/components/Home/Home.js
  src/components/Logged-out/LoggedOut.js
  src/components/Logged-out/LoggedOut.scss
  src/index.js
  src/services/Services.js
  src/services/auth.js
  src/services/history.js
Labels: enhancement

#8 App component doesn't allow authenticated user to visit routes
  src/components/App/App.js
  src/components/Board/Board.js
  src/components/Profile/Profile.js
Labels: bug

#10 boards explorer side-menu
  public/index.html
  src/components/App/App.js
  src/components/Board/Board.js
  src/components/Boards/Boards.js
  src/components/Boards/Boards.styles.js
  src/components/Boards/ZippyMenu/ZippyMenu.js
  src/components/Boards/ZippyMenu/ZippyMenu.styles.js
  src/components/Components.js
  src/components/Home/Home.js
  src/components/Profile/Profile.js
  src/components/Toolbar/Toolbar.js
  src/components/Toolbar/Toolbar.styles.js
Labels: enhancement

#12 Add a basic List and Cards components to the board page
  package-lock.json
  src/components/Board/Board.js
  src/components/Board/components/List/List.js
  src/components/Board/components/List/List.styles.js
  src/components/Board/components/List/components/CardTask/CardTask.js
  src/components/Board/components/List/components/CardTask/CardTask.styles.js
  src/components/Board/components/List/components/ListFooter/ListFooter.js
  src/components/Board/components/List/components/ListFooter/ListFooter.styles.js
  src/components/Board/components/List/components/ListHeader/ListHeader.js
  src/components/Board/components/List/components/ListHeader/ListHeader.styles.js
  src/components/Board/components/List/components/Modal/Modal.js
  src/components/Board/components/List/components/Modal/Modal.styles.js
  src/components/Board/components/List/components/index.js
  src/dummyData.js
Labels: enhancement

#13 removed <Toolbar /> from Board.js
  src/components/Board/Board.js
Labels: bug, quickfix
